"""Add is_active to models

Revision ID: 840c84f087a6
Revises: cde60e4cf6b8
Create Date: 2026-02-07 16:50:05.309000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840c84f087a6'
down_revision = 'cde60e4cf6b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))

    with op.batch_alter_table('classroom', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))

    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('classroom', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('academic_class', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
